/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-03 08:42:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Comparator;
import java.util.Arrays;
import java.io.File;

public final class ex21_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("java.util.Comparator");
    _jspx_imports_classes.add("java.io.File");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


	//디렉토리 탐색
	String path = application.getRealPath("/pic");
	
	File dir = new File(path);
	File[] list = dir.listFiles();
	
	//시간 순서대로 정렬
	//System.out.println(list[0].lastModified());
	
	/* 
	Arrays.sort(list, new Comparator<File>() {
		public int compare(File o1, File o2) {
			return Long.compare(o1.lastModified(), o2.lastModified());
		}
	}); 
	*/
	
	Arrays.sort(list, (o1, o2) -> Long.compare(o2.lastModified(), o1.lastModified()));


      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://pinnpublic.dothome.co.kr/cdn/example-min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("	#list {\r\n");
      out.write("		/* outline: 10px solid black; */\r\n");
      out.write("		width: 750px;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-wrap: wrap;\r\n");
      out.write("		padding: 0;\r\n");
      out.write("		margin-left: 25px;\r\n");
      out.write("	}\r\n");
      out.write("	#list > div {\r\n");
      out.write("		border: 1px solid #999;\r\n");
      out.write("		width: 126px;\r\n");
      out.write("		height: 126px;\r\n");
      out.write("		margin: 11px;\r\n");
      out.write("		background-size: cover;\r\n");
      out.write("		background-repeat: no-repeat;\r\n");
      out.write("		background-position: center center;\r\n");
      out.write("		position: relative;\r\n");
      out.write("		left: 0;\r\n");
      out.write("		top: 0;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#list > div > span {\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		right: 5px;\r\n");
      out.write("		top: 0;\r\n");
      out.write("		font-size: 1.5rem;\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("		display: none;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#list > div:hover > span {\r\n");
      out.write("		display: inline;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#img1 {\r\n");
      out.write("		max-width: 490px;\r\n");
      out.write("		display: block;\r\n");
      out.write("		margin: 15px auto;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- ex21.jsp -->\r\n");
      out.write("	<!--  \r\n");
      out.write("		1. 이미지 확대 보기(모달창)\r\n");
      out.write("		2. 이미지 정렬\r\n");
      out.write("	-->\r\n");
      out.write("	<h1>Image Gallery</h1>\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"list\">\r\n");
      out.write("		");
 for (File file : list) { 
      out.write("\r\n");
      out.write("		<div style=\"background-image:url(pic/");
      out.print( file.getName() );
      out.write(");\" data-modal-button=\"view\" data-filename=\"");
      out.print( file.getName() );
      out.write("\">\r\n");
      out.write("			<span title=\"delete\" \r\n");
      out.write("			onclick=\"del('");
      out.print( file.getName() );
      out.write("');\">&times;</span>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div data-modal-window=\"view\" data-modal-title=\"Image\">\r\n");
      out.write("		<img id=\"img1\">\r\n");
      out.write("		<hr>\r\n");
      out.write("		<div>\r\n");
      out.write("			<button class=\"ok\" data-modal-ok=\"view\">확인</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<hr>\r\n");
      out.write("	\r\n");
      out.write("	<form method=\"POST\" action=\"ex21_ok.jsp\"\r\n");
      out.write("		enctype=\"multipart/form-data\">\r\n");
      out.write("	<table class=\"vertical\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>이미지</th>\r\n");
      out.write("			<td><input type=\"file\" name=\"attach\" required></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<div>\r\n");
      out.write("		<input type=\"submit\" value=\" 이미지 업로드 \">\r\n");
      out.write("	</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("	<script src=\"http://pinnpublic.dothome.co.kr/cdn/example-min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("		function del(filename) {\r\n");
      out.write("			//alert(filename);\r\n");
      out.write("			\r\n");
      out.write("			if (confirm('delete?')) {\r\n");
      out.write("				location.href = 'ex21_del.jsp?filename=' + filename;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function show(filename) {\r\n");
      out.write("			alert(filename);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		document.querySelectorAll('#list > div').forEach((item) => {\r\n");
      out.write("			item.addEventListener('click', function() {\r\n");
      out.write("				//alert(event.target.dataset['filename']);\r\n");
      out.write("				$('#img1').attr('src'\r\n");
      out.write("				, '/jsp/pic/' + event.target.dataset['filename']);\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
